# Generated by Django 4.2.9 on 2024-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_options_event_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('json_object', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
